[package]
name = "amqpr-api"
version = "0.1.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]
description = "A tokio based amqp api library mainly used by amqpr."
repository = "https://github.com/AtsukiTak/amqp-api"
keywords = ["amqp", "rabbitmq"]
categories = ["network-programming", "amqp", "rabbitmq"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"

bytes = "0.4"

error-chain = "0.10"
log4rs = "0.7"
log = "0.3"

amqpr-codec = "0.1"
